// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhNImk-UkgihI4VuDw3bputnoh4yWtVqg',
    appId: '1:1014824460743:web:7022f048a1b9b214ba79e2',
    messagingSenderId: '1014824460743',
    projectId: 'jobs-bd-12960',
    authDomain: 'jobs-bd-12960.firebaseapp.com',
    storageBucket: 'jobs-bd-12960.appspot.com',
    measurementId: 'G-V55Y572RBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi583R3whmIrLmTcGHsBVj1gOoxPbVn1c',
    appId: '1:1014824460743:android:7e15263771031f91ba79e2',
    messagingSenderId: '1014824460743',
    projectId: 'jobs-bd-12960',
    storageBucket: 'jobs-bd-12960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5A1FCJ3hia9vEKdZfLw_RM_tFHkAH4Ng',
    appId: '1:1014824460743:ios:44092126920b82b1ba79e2',
    messagingSenderId: '1014824460743',
    projectId: 'jobs-bd-12960',
    storageBucket: 'jobs-bd-12960.appspot.com',
    iosBundleId: 'com.royalcourtbd.jobsBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5A1FCJ3hia9vEKdZfLw_RM_tFHkAH4Ng',
    appId: '1:1014824460743:ios:44092126920b82b1ba79e2',
    messagingSenderId: '1014824460743',
    projectId: 'jobs-bd-12960',
    storageBucket: 'jobs-bd-12960.appspot.com',
    iosBundleId: 'com.royalcourtbd.jobsBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhNImk-UkgihI4VuDw3bputnoh4yWtVqg',
    appId: '1:1014824460743:web:9feaed110f2ac913ba79e2',
    messagingSenderId: '1014824460743',
    projectId: 'jobs-bd-12960',
    authDomain: 'jobs-bd-12960.firebaseapp.com',
    storageBucket: 'jobs-bd-12960.appspot.com',
    measurementId: 'G-YMP25BL1FD',
  );
}
